<a href="https://colab.research.google.com/github/imomchaubey/pyhon_assignment89/blob/main/assignment_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a. Addition of 2 in all the element
b. Multiply 3 with all the elements
c. Divide every element by 2


In [1]:
import numpy as np

#  a NumPy array with 5 elements
arr = np.array([1, 2, 3, 4, 5])

# Addition of 2 to all elements
add_2 = arr + 2

# Multiply 3 with all elements
multiply_3 = arr * 3

# Divide every element by 2
divide_2 = arr / 2

print("Original array of these numbers :", arr)
print("After adding 2 to these numbers :", add_2)
print("After multiplying by 3 to these numbers:", multiply_3)
print("After dividing by 2 to these numbers:", divide_2)


Original array of these numbers : [1 2 3 4 5]
After adding 2 to these numbers : [3 4 5 6 7]
After multiplying by 3 to these numbers: [ 3  6  9 12 15]
After dividing by 2 to these numbers: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:
a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
import numpy as np

# Given array
arr = np.array([1, 2, 3, 6, 4, 5])

# Reverse the array
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


b. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent value and their indices
mode_x = mode_values[0]
indices_x = np.where(x == mode_x)[0]
print("Most frequent values =", mode_x)
print("Their values =", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent values and their indices
modes_indices_y = [(val, np.where(y == val)[0]) for val in mode_values]
print(modes_indices_y)
print(mode_values)

Most frequent values = 1
Their values = [0 5 7 8 9]
[(1, array([0, 1, 2])), (3, array([4, 8, 9]))]
[1 3]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a. Access 1st row, 2nd column
b. Access 3rd row, 1st column


In [4]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
element_1 = arr[0, 1]
print(f"Element at 1st row, 2nd column: {element_1}")

# b) Access 3rd row, 1st column
element_2 = arr[2, 0]
print(f"Element at 3rd row, 1st column: {element_2}")


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [5]:
import numpy as np

Omprakash = np.linspace(10, 100, 25)

dimensions = Omprakash.ndim
shape = Omprakash.shape
total_elements = Omprakash.size
data_type = Omprakash.dtype
bytes_consumed = Omprakash.nbytes

print("Array:", Omprakash)
print("Dimensions:", dimensions)
print("Shape:", shape)
print("Total elements:", total_elements)
print("Data type:", data_type)
print("Bytes consumed:", bytes_consumed)

transpose_reshape = Omprakash.reshape(25, 1)
transpose_T = Omprakash.T

print("\nTranspose using reshape():\n", transpose_reshape)
print("\nTranspose using T attribute:\n", transpose_T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Bytes consumed: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [6]:
import numpy as np

# Create the 2-D array
ucs420_Omprakash = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

# Compute mean, median, max, min, unique elements
mean_val = np.mean(ucs420_Omprakash)
median_val = np.median(ucs420_Omprakash)
max_val = np.max(ucs420_Omprakash)
min_val = np.min(ucs420_Omprakash)
unique_elements = np.unique(ucs420_Omprakash)

print("Array:\n", ucs420_Omprakash)
print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_elements)

# Reshape the array to four rows and three columns
reshaped_ucs420_Omprakash = ucs420_Omprakash.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_Omprakash)

# Resize the array to two rows and three columns
resized_ucs420_Omprakash = np.resize(ucs420_Omprakash, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_Omprakash)

Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
